name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-gi \
          python3-gi-cairo \
          gir1.2-gtk-4.0 \
          gir1.2-adwaita-1 \
          libgtk-4-1 \
          libadwaita-1-0

    - name: Validate manifest
      run: |
        python3 -c "import json; print('✅ Manifest valid'); json.load(open('io.github.ublue.RebaseTool.json'))"

    - name: Check Python syntax
      run: |
        python3 -m py_compile src/ublue-image-manager.py
        python3 -m py_compile src/command_executor.py
        python3 -m py_compile src/deployment_manager.py
        python3 -m py_compile src/rpm_ostree_helper.py
        python3 -m py_compile src/history_manager.py
        python3 -m py_compile src/progress_tracker.py
        python3 -m py_compile src/ui/simple_confirmation_dialog.py
        python3 -m py_compile src/ui/confirmation_dialog.py
        echo "✅ All Python files compile successfully"

    - name: Test imports
      run: |
        python3 -c "
import sys
sys.path.insert(0, 'src')
import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
print('✅ GTK4/Adwaita imports successful')
"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install linters
      run: |
        pip install flake8 black isort

    - name: Run flake8
      run: |
        flake8 src/ --max-line-length=120 --ignore=E501,W503 || true

    - name: Check black formatting
      run: |
        black --check src/ --line-length=120 || true

    - name: Check import sorting
      run: |
        isort --check-only src/ || true